export const shoesdetail = [
  {
    id: 1,
    img: "images/converse.jpg",
    name: "Converse",
    price: "45.0",
    color: "Grey White in color",
    quantity: 1,
    showdata: 45.0,
  },
  {
    id: 2,
    img: "images/jordan.jpg",
    name: "Jordan",
    price: "45.0",
    color: "Red in color",
    quantity: 1,
    showdata: 45.0,
  },
  {
    id: 3,
    img: "images/newbalance.jpg",
    name: "Skechers",
    price: "55.0",
    color: "Blue in color",
    quantity: 1,
    showdata: 55.0,
  },
  {
    id: 4,
    img: "images/Nike.jpg",
    name: "Nike",
    price: "65.0",
    color: "Orange & White in color",
    quantity: 1,
    showdata: 55.0,
  },
  {
    id: 5,
    img: "images/puma.jpg",
    name: "Puma",
    price: "45.0",
    color: "white in color",
    quantity: 1,
    showdata: "",
  },
  {
    id: 6,
    img: "images/fila.jpg",
    name: "Fila",
    price: "45.0",
    color: "White in color",
    quantity: 1,
    showdata: 55.0,
  },
  {
    id: 7,
    img: "images/Skechers.jpg",
    name: "NewBalance",
    price: "39.0",
    color: "White in color",
    quantity: 1,
    showdata: 39.0,
  },
  {
    id: 8,
    img: "images/adidas.jpg",
    name: "Adidas",
    price: "75.0",
    color: "White Red in color",
    quantity: 1,
    showdata: 75.0,
  },
];
